apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mongo
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: mongo
    spec:
      containers:
        - image: mongo
          name: mongo
          resources: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
  selector:
    run: mongo
  type: NodePort
status:
  loadBalancer: {}
